name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Arjun@123
          POSTGRES_DB: document_management_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Run linting
      #   run: npm run lint

      - name: Run tests
        run: npm test
        env:
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: Arjun@123
          DATABASE_NAME: document_management_test
          JWT_SECRET: test_jwt_secret
          JWT_EXPIRATION: 3600

      # - name: Run e2e tests
      #   run: npm run test:e2e
      #   env:
      #     DATABASE_HOST: postgres
      #     DATABASE_PORT: 5432
      #     DATABASE_USERNAME: postgres
      #     DATABASE_PASSWORD: Arjun@123
      #     DATABASE_NAME: document_management_test
      #     JWT_SECRET: test_jwt_secret
      #     JWT_EXPIRATION: 3600

  build:
    runs-on: ubuntu-latest
    needs: test
    # Optional: Only push to Docker Hub on push to main
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: yourusername/document-management:latest